### ISSUE TITLE
Italian translation (and maybe a problem for others)

### ISSUE THREAD

**Issue by filochard** [thothix/guayadeque#18]
Hi Tiago 
Working on Italian translation I find something that seems difficult to understand and to translate (I  think that maybe I will have to modify the French and Greek translations too if I didn't understand it well)
NB these messages don't appear anywhere when I use the Guayadeque GUI

here it is
#: ui/preferences/Preferences.cpp:527
msgid "Drop files clear playlist"

Several meanings are possible even  in English ... I am stuck to know what is the real meaning of this : 
Is it : 
depositing  files add them to the playlist ?
or 
depositing  files erase the playlist ?
or
suppressing files rid the playlist of them ?
or
suppressing files erase the playlist ?

-------------------------------------------

and this one
#: ui/preferences/Preferences.cpp:557
msgid "Close to task bar icon"

does it means : 
Put the close icon to the task bar ?
or 
Near the task bar icon ?

-----------------------------------
and this one
#: ui/preferences/Preferences.cpp:884
msgid "Tracks left to start search"
 
does it means : 
the search begins except for some tracks 

-------------------------------------------

and this one
#: ui/preferences/Preferences.cpp:909
msgid "Don't repeat last"
Don't repeat the last one
or
Don't repeat the last ones

-----------------------------------

and this strange one

#: ui/lyrics/LyricsPanel.cpp:82 ui/lastfmpanel/LastFMPanel.cpp:1625
msgid "Follow player"
Does it mean continue playing ?
or 
Follow the playing file of the player?

-------------------------------------------- 
a typo in the pot file ?
2009 #: ui/MainFrame.cpp:1327
2010 msgid "Show/Hide the locatons"                 ----------- do you mean locations
2011 msgstr ""

--------------------------------------------------------------

**Comment by filochard** [comment]
ITALIAN TRANSLATION
================================
Here is an Italian po file synchronized with the pot file
[it-guayadeque.po.txt](https://github.com/user-attachments/files/17882000/it-guayadeque.po.txt)

It will perhaps need little corrections because of https://github.com/thothix/guayadeque/issues/18#issue-2685935969

**Comment by thothix** [comment]
Hi @filochard 

> 
> here it is #: ui/preferences/Preferences.cpp:527 msgid "Drop files clear playlist"
> 

It's in Preferences -> General

> Several meanings are possible even in English ... I am stuck to know what is the real meaning of this : Is it : depositing files add them to the playlist ? or depositing files erase the playlist ? or suppressing files rid the playlist of them ? or suppressing files erase the playlist ?
> 

Maybe change it to something like "Clear playlist when drag and drop files to it"

> and this one #: ui/preferences/Preferences.cpp:557 msgid "Close to task bar icon"
> 
> does it means : Put the close icon to the task bar ? or Near the task bar icon ?
> 

I don't know a better way to say "Close to taskbar icon", maybe "Close keeps the taskbar icon".
"Close to taskbar icon" is the most common way in english. Many applications have this feature, maybe you can look to another application to see how it refers to it in french.

> and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> 
> does it means : the search begins except for some tracks
> 

something like:
Number of tracks remaining to start search.

> and this one #: ui/preferences/Preferences.cpp:909 msgid "Don't repeat last" Don't repeat the last one or Don't repeat the last ones
> 

It's right this way. The context in preferences is:
"Don't repeat last 20 artists"

> and this strange one
> 
> #: ui/lyrics/LyricsPanel.cpp:82 ui/lastfmpanel/LastFMPanel.cpp:1625 msgid "Follow player" Does it mean continue playing ? or Follow the playing file of the player?
> 

Yes, it means "Follow the playing file of the player"

> a typo in the pot file ? 2009 #: ui/MainFrame.cpp:1327 2010 msgid "Show/Hide the locatons" ----------- do you mean locations 2011 msgstr ""

Fixed

**Comment by filochard** [comment]
> Hi @filochard

> > here it is #: ui/preferences/Preferences.cpp:527 msgid "Drop files clear playlist"

> Maybe change it to something like "Clear playlist when drag and drop files to it"

That sounds better for translation
> 
> > and this one #: ui/preferences/Preferences.cpp:557 msgid "Close to task bar icon"
> > does it means : Put the close icon to the task bar ? or Near the task bar icon ?
> 
> I don't know a better way to say "Close to taskbar icon", maybe "Close keeps the taskbar icon". "Close to taskbar icon" is the most common way in english. Many applications have this feature, maybe you can look to another application to see how it refers to it in french.

Thanks 
I had not understood that it was linked to "activate  task bar icon" (I never used this) 
The translation is now easy for me

> 
> > and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> > does it means : the search begins except for some tracks
> 
> something like: Number of tracks remaining to start search.

This would be easier to understand and to translate
> 
> > and this one #: ui/preferences/Preferences.cpp:909 msgid "Don't repeat last" Don't repeat the last one or Don't repeat the last ones
> 
> It's right this way. The context in preferences is: "Don't repeat last 20 artists"

There is no plural in English for articles or adjectives...  for this reason we have to choose for translating "last" between "le dernier" or "les derniers"
> 

> > and this strange one
> > #: ui/lyrics/LyricsPanel.cpp:82 ui/lastfmpanel/LastFMPanel.cpp:1625 msgid "Follow player" Does it mean continue playing ? or Follow the playing file of the player?
> 
> Yes, it means "Follow the playing file of the player"

This would be more clear as this for translation
> 
> > a typo in the pot file ? 2009 #: ui/MainFrame.cpp:1327 2010 msgid "Show/Hide the locatons" ----------- do you mean locations 2011 msgstr ""
> 
> Fixed

**Comment by filochard** [comment]
Hi Tiago 
Thanks again for you help ;-)

> Hi @filochard
> 
> > here it is #: ui/preferences/Preferences.cpp:527 msgid "Drop files clear playlist"
> 
> It's in Preferences -> General
> 
> > Several meanings are possible even in English ... I am stuck to know what is the real meaning of this : Is it : depositing files add them to the playlist ? or depositing files erase the playlist ? or suppressing files rid the playlist of them ? or suppressing files erase the playlist ?
> 
> Maybe change it to something like "Clear playlist when drag and drop files to it"

Yes this would be easier to understand and translate
> 
> > and this one #: ui/preferences/Preferences.cpp:557 msgid "Close to task bar icon"
> > does it means : Put the close icon to the task bar ? or Near the task bar icon ?
> 
> I don't know a better way to say "Close to taskbar icon", maybe "Close keeps the taskbar icon". "Close to taskbar icon" is the most common way in english. Many applications have this feature, maybe you can look to another application to see how it refers to it in french.
> 

I had not realized that it is linked to "activate task bar icon"  (I never marked this box)
It's clearer for me
> > and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> > does it means : the search begins except for some tracks
> 
> something like: Number of tracks remaining to start search.

This would be clearer too
> 
> > and this one #: ui/preferences/Preferences.cpp:909 msgid "Don't repeat last" Don't repeat the last one or Don't repeat the last ones
> 
> It's right this way. The context in preferences is: "Don't repeat last 20 artists"

The difficulty is that in English there is no plural for articles or adjectives or past pariciples
"Last" may be translated as "le dernier" or as "les derniers" depending of the context
> 
> > and this strange one
> > #: ui/lyrics/LyricsPanel.cpp:82 ui/lastfmpanel/LastFMPanel.cpp:1625 msgid "Follow player" Does it mean continue playing ? or Follow the playing file of the player?
> 
> Yes, it means "Follow the playing file of the player"
> 

That would be clearer too
> > a typo in the pot file ? 2009 #: ui/MainFrame.cpp:1327 2010 msgid "Show/Hide the locatons" ----------- do you mean locations 2011 msgstr ""
> 
> Fixed

**Comment by thothix** [comment]
> 
> > > and this one #: ui/preferences/Preferences.cpp:557 msgid "Close to task bar icon"
> > > does it means : Put the close icon to the task bar ? or Near the task bar icon ?
> > 
> > 
> > I don't know a better way to say "Close to taskbar icon", maybe "Close keeps the taskbar icon". "Close to taskbar icon" is the most common way in english. Many applications have this feature, maybe you can look to another application to see how it refers to it in french.
> 
> I had not realized that it is linked to "activate task bar icon" (I never marked this box) It's clearer for me
> 
I'm going to move "Close to taskbar icon" and put it right below the  "activate task bar icon" because it depends on it to be enabled.

A More clear explanation should be:
Keeps the  application running in the taskbar when it is closed.

> > > and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> > > does it means : the search begins except for some tracks
> > 
> > 
> > something like: Number of tracks remaining to start search.
> 
> This would be clearer too
> 

Even better: Number of remaining tracks needed to start search.

> > > and this one #: ui/preferences/Preferences.cpp:909 msgid "Don't repeat last" Don't repeat the last one or Don't repeat the last ones
> > 
> > It's right this way. The context in preferences is: "Don't repeat last 20 artists"
> 
> The difficulty is that in English there is no plural for articles or adjectives or past pariciples "Last" may be translated as "le dernier" or as "les derniers" depending of the context
> 

I changed to use plural for this message. The translation looks like this now:

#: Preferences.cpp:1036
msgid "Don't repeat last"
msgid_plural "Don't repeat last"
msgstr[0] "Ne pas répéter le dernier"
msgstr[1] "Ne pas répéter les derniers"

We need to provide a singular and a plural for this message. 
Correct the above if the plural is wrong please.
(In this case the singular and the plural are the same in English)

**Comment by filochard** [comment]
> 
> I'm going to move "Close to taskbar icon" and put it right below the "activate task bar icon" because it depends on it to be enabled.
> 
> A More clear explanation should be: Keeps the application running in the taskbar when it is closed.
> 

Good idea

> > > > and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> > > > does it means : the search begins except for some tracks
> > > 
> > > 
> > > something like: Number of tracks remaining to start search.
> > 
> > 
> > This would be clearer too
> 
> Even better: Number of remaining tracks needed to start search.
> 

Better indeed
> > > > and this one #: ui/preferences/Preferences.cpp:909 msgid "Don't repeat last" Don't repeat the last one or Don't repeat the last ones
> > > 
> > > 
> > > It's right this way. The context in preferences is: "Don't repeat last 20 artists"
> > 
> > 
> > The difficulty is that in English there is no plural for articles or adjectives or past pariciples "Last" may be translated as "le dernier" or as "les derniers" depending of the context
> 
> I changed to use plural for this message. The translation looks like this now:
> 
> #: Preferences.cpp:1036 msgid "Don't repeat last" msgid_plural "Don't repeat last" msgstr[0] "Ne pas répéter le dernier" msgstr[1] "Ne pas répéter les derniers"
> 
> We need to provide a singular and a plural for this message. Correct the above if the plural is wrong please. (In this case the singular and the plural are the same in English)

The translation is right for the plural

**Comment by filochard** [comment]
Hi again Tiago
> > > > > and this one #: ui/preferences/Preferences.cpp:884 msgid "Tracks left to start search"
> > > > > does it means : the search begins except for some tracks
> > > > 
> > > > 
> > > > something like: Number of tracks remaining to start search.
> > > 
> > > 
> > > This would be clearer too
> > 
> > 
> > Even better: Number of remaining tracks needed to start search.
> 

I am very sorry
The translation from English is not always very clear for me because sometimes the word "of" is missing,  replaced by the order of the words in a phrase : 
- sometimes the meaning is  evident fro example "album cover" means "cover of the album" and nothing else (cover is surely a noun and not a verb otherwise it would be written covers)
- but a contrario "albums cover" may mean "cover of the albums" or "the " albums are covering" depending of the context
and "album covers" may mean "covers of the album" or "album is covering"

For this reason I'm always stuck with this : "Tracks left to start search" (I can't find where this message may appear) : 
could the meaning be indeed : "Search of the tracks waiting to start" 
or more precisely "Search of the tracks not having been started yet" 
Since I don't know the context I don't know how to translate it in French( where there is always "de" for "of"), Italian and in Greek .

-----------------------------------------------------------------------------------------
Out of topic
  I never thought that English was an accurate language
 In Greek there is at least never such confusions since the nouns have a declension and their spelling depends of their function in a sentence and their place is not important : 
- nominative case δίσκος (subject of the verb )  : the disk is full =    ο δίσκος είναι γεμάτος or είναι γεμάτος ο δίσκος 
-  accusative case δίσκον (direct object of the verb),  : give the disk = δίνει τον δίσκον
- genitive case δίσκου (indicating for this noun the possession of an other noun), : the cover of the disk = the disk cover
το εξώφυλλο του δίσκου = του δίσκου εξώφυλλο  = το εξώφυλλο δίσκου
- -dative case δίσκο (indirect object of the verb), :  add a track to the disk = προσθέστε ένα κομμάτι στο δίσκο 

and the verbs deriving from a noun have their own endings :   the cover = η κάλυψη     I cover=καλύπτω

NB there are too two words for a cover : for a disk cover it's εξώφυλλο but  for a bed cover it's κάλυψη

**Comment by filochard** [comment]
Hi Tiago
This issue is beginning to be too long since most of the comments have been resolved

it can be resumed with only two problems remaining now : 

1 #: ui/preferences/Preferences.cpp:881 msgid "Number of remaining tracks needed to start search"
NB I didn't find where this message may appear inside Guayadeque and can't understand what it means really

Needing maybe to be replaced  by "Search of the tracks not having been started yet" 
for a better understanding by translators 
proposed translations if this msgid is OK for you : 
- in French msgstr "Recherche des morceaux restant à jouer"
- in Italian msgstr "Cerca i brani che non sono ancora stati riprodotti"
- in Greek msgstr "Αναζήτηση των κομματιών που δεν έχουν αναπαραχθεί ακόμα"

2#: ui/preferences/Preferences.cpp:557 msgid "Close to taskbar icon"
Needing to be clearer for the translators too, maybe "Close and reduce to its taskbar icon"
proposed translations  if this msgid is OK for you: 
- in French msgstr "Fermer et réduire à son icône sur la barre de tâches"
- in Italaian msgstr "Chiudere e ridurre all'icona della barra delle applicazioni"
NB there was a big misinterpretation in the previous Italian translation from 2013 that I had kept as it was
- in Greek msgstr "Κλείσιμο και μείωση στο εικονίδιο της γραμμής εργασιών"


If you agree with these clarifications this issue should be closed

When it's closed we can open a new issue for little remaining translation difficulties

**Comment by thothix** [comment]
> 
> 1 #: ui/preferences/Preferences.cpp:881 msgid "Number of remaining tracks needed to start search" NB I didn't find where this message may appear inside Guayadeque and can't understand what it means really
> 

![image](https://github.com/user-attachments/assets/80b9de34-a248-4f9d-a603-4e538229aee3)

> Needing maybe to be replaced by "Search of the tracks not having been started yet" for a better understanding by translators proposed translations if this msgid is OK for you :
> 
That's not the actual meaning for the action. I don't know a better explanation that the current one.
What the config means is "it start search for more tracks when the number of tracks in playlist reach this value/number".
I understand this from "Number of remaining tracks needed to start search" if I look at the preferences screen.
It's difficult to describe this without the context (the smart play mode)

Maybe:
"Number of remaining tracks needed to start adding new ones"
"Remaining tracks required for new addition"

**Comment by thothix** [comment]
> 2#: ui/preferences/Preferences.cpp:557 msgid "Close to taskbar icon" Needing to be clearer for the translators too, maybe "Close and reduce to its taskbar icon" proposed translations if this msgid is OK for you:
> 
>     * in French msgstr "Fermer et réduire à son icône sur la barre de tâches"
> 
>     * in Italaian msgstr "Chiudere e ridurre all'icona della barra delle applicazioni"
>       NB there was a big misinterpretation in the previous Italian translation from 2013 that I had kept as it was
> 
>     * in Greek msgstr "Κλείσιμο και μείωση στο εικονίδιο της γραμμής εργασιών"

"Close to taskbar icon" is a expression I see since 90's. Actually the more common expression is "Close to System Tray".
It started to be used in Windows 95 (Windows 3 didn't have a taskbar). Some applications use an even simpler expression "Enable Tray" as I see for example in CopyQ (it's currently installed in my system; It doesn't have a "Close to Tray" because it's mandatory).
It's common use "Close" word because some applications have the minimize option also: "Minimize to System Tray".

**Comment by thothix** [comment]
Some options to "Close to taskbar icon":
"Close minimizes to taskbar icon"
"Close minimizes to system tray"

I prefer "system tray" because "taskbar icon" is another thing to me but it can be used.
Example:

![image](https://github.com/user-attachments/assets/26410d3d-3e1d-42e6-8166-10b3b6cc0ea2)

**Comment by filochard** [comment]
> > 1 #: ui/preferences/Preferences.cpp:881 msgid "Number of remaining tracks needed to start search" NB I didn't find where this message may appear inside Guayadeque and can't understand what it means really
> 
> ![image](https://private-user-images.githubusercontent.com/42182417/390488343-80b9de34-a248-4f9d-a603-4e538229aee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDE3MjEsIm5iZiI6MTczMjc0MTQyMSwicGF0aCI6Ii80MjE4MjQxNy8zOTA0ODgzNDMtODBiOWRlMzQtYTI0OC00ZjlkLWE2MDMtNGU1MzgyMjlhZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIxMDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMmFjZmZmYWIwNmVmOGRiYzMyYTNlNWJiZGFmN2ZmODNiMWI5NWUwZDdlMDNlYWY0OWIzZDA1Nzg5YTcyMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JMlbSEECpPUObb70rVfGNHY9T614_828UTVCqz0aVgM)
> 
> > Needing maybe to be replaced by "Search of the tracks not having been started yet" for a better understanding by translators proposed translations if this msgid is OK for you :
> 
> That's not the actual meaning for the action. I don't know a better explanation that the current one. What the config means is "it start search for more tracks when the number of tracks in playlist reach this value/number". I understand this from "Number of remaining tracks needed to start search" if I look at the preferences screen. It's difficult to describe this without the context (the smart play mode)
> 
> Maybe: "Number of remaining tracks needed to start adding new ones" "Remaining tracks required for new addition"

Hi Tiago 
Thanks for your patience

Thanks for this enlightment : I didn't know where this was and that it concerned the preference for random play or smart mode 
For me now this would be clearer and easier to translate in any language
This could be : 
msgid "Number of tracks required to start random play or intelligent mode"
for which these translations might be OK now
- for French msgstr "Nombre de pistes nécessaires pour démarrer la lecture aléatoire ou le mode intelligent"
- for Italian msgstr "Numero di brani necessari per avviare la riproduzione casuale o la modalità intelligente"
- for Greek msgstr "Αριθμός κομματιών που απαιτούνται για την έναρξη τυχαίας αναπαραγωγής ή έξυπνης λειτουργίας"

This problem seems being solved now  :o)

**Comment by filochard** [comment]
> Some options to "Close to taskbar icon": "Close minimizes to taskbar icon" "Close minimizes to system tray"
> 
> I prefer "system tray" because "taskbar icon" is another thing to me but it can be used. Example:
> 
> ![image](https://private-user-images.githubusercontent.com/42182417/390518363-26410d3d-3e1d-42e6-8166-10b3b6cc0ea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDE3MjEsIm5iZiI6MTczMjc0MTQyMSwicGF0aCI6Ii80MjE4MjQxNy8zOTA1MTgzNjMtMjY0MTBkM2QtM2UxZC00MmU2LTgxNjYtMTBiM2I2Y2MwZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIxMDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWI4NDY2OGQyNGIxYTMyNDJlMzNiNmEzNGIwMzAzN2Y3MTAxZTIzYzA1N2VmNDlkMTliOTZkOTliNmFjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q2FbS38ASdGfbjVyNjG1IpnUeEF79KpkXKxEo-WG1aw)

You are totally right : the system tray is indeed the place where the icon can be activated 
and when it is activated  the "Close  minimizes to system tray icon" let this icon in this place

Besides this, when Guayadeque is running, he taskbar itself contains already always a little box with guayadeque name
![taskbar-guayadeque-running](https://github.com/user-attachments/assets/448c874e-0cf3-4f67-9c3c-e49b37ea3419)

The msgid might be clear now, perhaps adding its because this icon must have been activated fist
msgid "Close minimizes to **its** system tray icon"

and the translations may be
- for French msgstr "Fermer le programme le réduit à son icône dans la zone de notifications (system tray)"
- for Italian msgstr "La chiusura del programma lo riduce alla sua icona nell'area di notifica (system tray)"
- for Greek msgstr "Το κλείσιμο του προγράμματος το περιορίζει στο εικονίδιό του στη ζώνη ειδοποιήσεων (system tray)"

If you agree with those two solutions we may close this long issue
let me know
And thanks again

**Comment by filochard** [comment]
Post scriptum
msgid "Activate taskbar icon" should be modified too into

msgid "Activate system tray icon"
and translations
- for French msgstr "Activer l'icône dans la zone de notifications (system tray)"
- for Italian msgstr "Attivare l'icona nell'area di notifica (system tray)"
- for Greek msgstr "Ενεργοποίηση του εικονιδίου στη ζώνη ειδοποιήσεων (system tray)"

**Comment by thothix** [comment]
> 
> Thanks for this enlightment : I didn't know where this was and that it concerned the preference for random play or smart mode For me now this would be clearer and easier to translate in any language This could be : msgid "Number of tracks required to start random play or intelligent mode" for which these translations might be OK now
> 
>     * for French msgstr "Nombre de pistes nécessaires pour démarrer la lecture aléatoire ou le mode intelligent"
> 
>     * for Italian msgstr "Numero di brani necessari per avviare la riproduzione casuale o la modalità intelligente"
> 
>     * for Greek msgstr "Αριθμός κομματιών που απαιτούνται για την έναρξη τυχαίας αναπαραγωγής ή έξυπνης λειτουργίας"

I'm still not happy with this message: "Number of tracks required to start random play or intelligent mode" .
First we don't need to refer to "random play or intelligent mode" because the option is already about this.
Besides this, the option don't "start" the intelligent mode (intelligent mode is started (enabled) in the player Smart button ), it defines when new tracks will be added.

I think we need something like: 
"Number of tracks required to start adding new tracks"
"Number of tracks required to start adding random tracks to the playlist"
"Minimum number of tracks required to start adding new ones"

**Comment by thothix** [comment]
Messages related to system tray are already updated.

**Comment by filochard** [comment]
> I'm still not happy with this message: "Number of tracks required to start random play or intelligent mode" . First we don't need to refer to "random play or intelligent mode" because the option is already about this. Besides this, the option don't "start" the intelligent mode (intelligent mode is started (enabled) in the player Smart button ), it defines when new tracks will be added.
> 
> I think we need something like: "Number of tracks required to start adding new tracks" "Number of tracks required to start adding random tracks to the playlist" "Minimum number of tracks required to start adding new ones"

Thanks again
I have tested Guayadeque modifying the number of tracks (1 or 2 or 3 or 4) in preference for Random/Smart Play 

There were no difference for Smart Mode: it always adds smartly new tracks to the playlist of the player whatever this number is.

Besides this Randomize never adds a track : it only modify the order of the existing tracks in the playlist of the player but of course you need to have a minimum number of tracks in this player (at least 3 in total that means 2  to move beside the track already playing)


msgid "Minimum number of tracks required for these modes" might satisfy both of these modes
Or more precisely
msgid "Minimum number of tracks required for the Random Play" would be more exact since this number has no impact for Smart Mode

**Comment by thothix** [comment]
> Thanks again I have tested Guayadeque modifying the number of tracks (1 or 2 or 3 or 4) in preference for Random/Smart Play
> 
> There were no difference for Smart Mode: it always adds smartly new tracks to the playlist of the player whatever this number is.
> 

I tested and it's all working fine to me. It adds the configured number of tracks when I have the minimum number of tracks in the playlist otherwise it doesn't add any tracks. If I disable the Smart mode it doesn't add any tracks at all.

> Besides this Randomize never adds a track : it only modify the order of the existing tracks in the playlist of the player but of course you need to have a minimum number of tracks in this player (at least 3 in total that means 2 to move beside the track already playing)
> 

Are you talking about the Randomize button in the playlist? This you are describing is the behavior it should have. It doesn't change the behavior of tracks added to the playlist, it only shuffle the tracks currently in the playlist.
Actually the name of this feature should be "Shuffle" (as most music players call it), not "Randomize" ...


> msgid "Minimum number of tracks required for these modes" might satisfy both of these modes Or more precisely msgid "Minimum number of tracks required for the Random Play" would be more exact since this number has no impact for Smart Mode

**Comment by filochard** [comment]
> > Besides this Randomize never adds a track : it only modify the order of the existing tracks in the playlist of the player but of course you need to have a minimum number of tracks in this player (at least 3 in total that means 2 to move beside the track already playing)
> 
> Are you talking about the Randomize button in the playlist? This you are describing is the behavior it should have. It doesn't change the behavior of tracks added to the playlist, it only shuffle the tracks currently in the playlist. Actually the name of this feature should be "Shuffle" (as most music players call it), not "Randomize" ...
> 
![randomize](https://github.com/user-attachments/assets/f9a5863c-dc92-4a32-aa89-03eeeec5b92e)
Yes I am talking of this
Indeed you are absolutely right :  this should be "Shuffle" instead of "Randomize"

**Comment by thothix** [comment]
Randomize renamed to Shuffle. One of these days I was thinking about rename it. Now is done and committed.

**Comment by filochard** [comment]
> >  I have tested Guayadeque modifying the number of tracks (1 or 2 or 3 or 4) in preference for Random/Smart Play
> > There were no difference for Smart Mode: it always adds smartly new tracks to the playlist of the player whatever this number is.
> 
> I tested and it's all working fine to me. It adds the configured number of tracks when I have the minimum number of tracks in the playlist otherwise it doesn't add any tracks. If I disable the Smart mode it doesn't add any tracks at all.
> 

![preferences](https://github.com/user-attachments/assets/3cc3c73f-3008-403c-ae97-f9a00407c4bc)
 
I understand only now what means in preferences the number in front of "Tracks left to start search"  
Indeed when it has been modified in preferences and accepted Guayadeque needs to be closed and started again so that this modification is taken into consideration... Changing it without stopping and restarting didn't change the behaviour of Smart Mode

This number indicates the
 "Number of the last tracks remaining to read, in the current playlist, that will be used to start a smart search"
or, a little, shorter
 "Last tracks remaining to read, in the current playlist, used to start a smart search"

This sentence is indeed very long to be clearer than "Tracks left to start search"  

And it is applied even if you shuffle the playlist when you have enabled the Smart Mode : new tracks are added when the playlist reading reaches the x last tracks (if x=3 for example the 3 last tracks)

To conclude
English is a concise language but full of possible misunderstandings

"Left" may mean for you :  "esquerda", or "a esquerda", or "abandonado" and for me "gauche" or "à gauche" or "laissé" or "quitté"

**Comment by filochard** [comment]
There's nothing more to clarify now
The last were not the least !

**Comment by thothix** [comment]
Yeah, left can be "The left direction, opposite of right" and can be "left, the past of leave".
As "right" can be the opposite of left and can be "the right thing, the correct thing" !!!

About the feature: to me it works only changing the values in preferences, no need to restart Guayadeque. Maybe there's some other factor like enabling/disabling the Smart mode that is interfering.

**Comment by filochard** [comment]
> Yeah, left can be "The left direction, opposite of right" and can be "left, the past of leave". As "right" can be the opposite of left and can be "the right thing, the correct thing" !!!
> 
> About the feature: to me it works only changing the values in preferences, no need to restart Guayadeque. Maybe there's some other factor like enabling/disabling the Smart mode that is interfering.

Your new "Number of remaining tracks needed to start adding new ones" is indeed better than my long sentence
It should be maybe "Number of tracks, remaining to read, needed to start adding new ones" not longer but even clearer

**Comment by filochard** [comment]
When the pot file is updated I can modify and synchronize French Greek and Italian translations
Is creating a "Pull request" the good way to provide them (the diff will be very little now that they are already synchronized with the last pot file)

**Comment by thothix** [comment]
> Your new "Number of remaining tracks needed to start adding new ones" is indeed better than my long sentence It should be maybe "Number of tracks, remaining to read, needed to start adding new ones" not longer but even clearer

I changed it a bit to "Minimum number of tracks to play required to add new ones"

**Comment by filochard** [comment]
> > Your new "Number of remaining tracks needed to start adding new ones" is indeed better than my long sentence It should be maybe "Number of tracks, remaining to read, needed to start adding new ones" not longer but even clearer
> 
> I changed it a bit to "Minimum number of tracks to play required to add new ones"

Nice you got it 

I think this issue may be closed now 

(need only to know if Pull requests are a good way to update the translations I propose)

**Comment by thothix** [comment]
There's a lot of conflics and you based your changes in a very outdated file.
I was able to merge French and Greek files manually but Italian is very different. You'll need to do it again based in the current translation.

You can send me the Italian .po again here.
I'm going to close the PR.

**Comment by thothix** [comment]
After that I think you can use Pull Requests to send updates, no problem.
I think it was my fault not to see your PR and I did a lot of changes after that.

**Comment by filochard** [comment]
Everything seems OK now for this issue
I have created a Pull Request for the French, Greek and Italian guayadeque.po files.
This comment may be closed now
